FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Muhammad Ali Akbar/Syed Ali Mashoud - Mock APi

This is an collection of APIS for a Task Manager System.
## Users Collection [/Users]

### Delete a User [Del]
+ Request (application/json)

        {
             "UName":"Ali Akbar",
             "erp":22950,
             "Batch":2024,
             "Program":"CS",
             "Gender":"Male",
             "age":21,
             "email":"ali@gmail.com",
             "PhoneNo":1234455343
        }
        
      

+ Response 201 (application/json)

    + Headers

            Location: /Tasks/

    + Body

            {
             "UName":"Ali Akbar",
             "erp":22950,
             "Batch":2024,
             "Program":"CS",
             "Gender":"Male",
             "age":21,
             "email":"ali@gmail.com",
             "PhoneNo":1234455343
            }

### Edit a User [PATCH]

+ Request (application/json)

        {
             "UName":"Ali Mashoud",
             "erp":22951,
             "Batch":2024,
             "Program":"CS",
             "Gender":"Male",
             "age":21,
             "email":"ali@gmail.com",
             "PhoneNo":1234455343
        }
        
      

+ Response 201 (application/json)

    + Headers

            Location: /Tasks/

    + Body

            {
             "UName":"Ali Mashoud",
             "erp":22951,
             "Batch":2024,
             "Program":"CS",
             "Gender":"Male",
             "age":21,
             "email":"ali@gmail.com",
             "PhoneNo":1234455343
            }




### List All Users [GET]

+ Response 200 (application/json)

        [
            {
             "UName":"Ali Akbar",
             "erp":22950,
             "Batch":2024,
             "Program":"CS",
             "Gender":"Male",
             "age":21,
             "email":"ali@gmail.com",
             "PhoneNo":1234455343
            }
        ]

### Create a New User [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
              "UName":"Ali Akbar",
             "erp":22950,
             "Batch":2024,
             "Program":"CS",
             "Gender":"Male",
             "age":21,
             "email":"ali@gmail.com",
             "PhoneNo":1234455343
        }

+ Response 201 (application/json)

    + Headers

            Location: /Tasks/

    + Body

            {
             "UName":"Ali Akbar",
             "erp":22950,
             "Batch":2024,
             "Program":"CS",
             "Gender":"Male",
             "age":21,
             "email":"ali@gmail.com",
             "PhoneNo":1234455343
            }
            
        


## Tasks Collection [/Tasks]

### Delete a Task [Del]
+ Request (application/json)

        {
             "TaskName":"Welcome Party",
                "Assignedto":"Ali",
                "Description":"Very Important",
                "Deadline":"25-3-2023",
                "Department":"CS" 
        }
        
      

+ Response 201 (application/json)

    + Headers

            Location: /Tasks/

    + Body

            {
                 "TaskName":"Welcome Party",
                "Assignedto":"Ali",
                "Description":"Very Important",
                "Deadline":"25-3-2023",
                "Department":"CS"
            }

### Edit an Task [PATCH]

+ Request (application/json)

        {
             "TaskName":"Beach Party",
                "Assignedto":"Hamnah",
                "Description":"Very Important",
                "Deadline":"25-3-2023",
                "Department":"CS" 
        }
        
      

+ Response 201 (application/json)

    + Headers

            Location: /Tasks/

    + Body

            {
                 "TaskName":"Beach Party",
                "Assignedto":"Hamnah",
                "Description":"Very Important",
                "Deadline":"25-3-2023",
                "Department":"CS"
            }




### List All Tasks [GET]

+ Response 200 (application/json)

        [
            {
                "TaskName":"Welcome Party",
                "Assignedto":"Ali",
                "Description":"Very Important",
                "Deadline":"25-3-2023",
                "Department":"CS"
            }
        ]

### Create a New Task [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
             "TaskName":"Welcome Party",
                "Assignedto":"Ali",
                "Description":"Very Important",
                "Deadline":"25-3-2023",
                "Department":"CS" 
        }

+ Response 201 (application/json)

    + Headers

            Location: /Tasks/

    + Body

            {
                 "TaskName":"Welcome Party",
                "Assignedto":"Ali",
                "Description":"Very Important",
                "Deadline":"25-3-2023",
                "Department":"CS"
            }
            
        

## Manager Collection [/managers]

### List All Managers [GET]

+ Response 200 (application/json)

        [
            {
                "Name": "abc",
                "erp": 12345,
                "Gender": 'M',
                "Phone Number": 1234567910,
                "Age": 20,
                "Email": "test@123.com",
                "Taskname": "TEST"
            }
        ]
        
## New Manager [/managers/add]

### Create a New Manager [POST]

+ Request (application/json)

        {
            "Name": "abc",
            "erp": 12345,
            "Gender": 'M',
            "Phone Number": 1234567910,
            "Age": 20,
            "Email": "test@123.com"
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "Message": "Manager Created"
            }
            
## Delete Manager [/managers/delete]

### Delete a Manager [POST]

+ Request (application/json)

        {
            "erp": 12345
        }
    
+ Response 201 (application/json)

        {
            "erp": 12345,
            "Message": "Deleted"
        }
        
## Update Info [/managers/update]
        
### Update an Info [POST]

+ Request (application/json)

        {  
            "Phone Number": 9876543210
        }
        
+ Response 201 (application/json)

        {
            "Phone Number": 9876543210,
            "Message": "Field Updated
        }